---

- name: Install common
  hosts: all
  tasks:

    - name: update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
      register: result

  #   - name: print stdout
  #     debug:
  #       msg: "{{ result.stdout }}"

  #   - name: check if a reboot is required
  #     shell: "[ -f /var/run/reboot-required ]"
  #     failed_when: False
  #     register: reboot_required
  #     changed_when: reboot_required.rc == 0
  #     notify: reboot

  # handlers:
  #   - name: reboot
  #     become: true
  #     command: /sbin/reboot
